-- -------------------------------------------------------------
-- 
-- File Name: foc_hdl_prj_v3\hdlsrc\FOC_Modified_v3\DQ_Current_Control.vhd
-- Created: 2017-11-28 19:11:02
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: DQ_Current_Control
-- Source Path: FOC_Modified_v3/DQ_Current_Control
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY DQ_Current_Control IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Q_Command                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
        D_Current                         :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En27
        Q_Current                         :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En27
        paramCurrentControlI              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En3
        paramCurrentControlP              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        sampleTime                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En24
        D_Voltage                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Q_Voltage                         :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En11
        );
END DQ_Current_Control;


ARCHITECTURE rtl OF DQ_Current_Control IS

  -- Component Declarations
  COMPONENT D_Current_Control
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Current_Command                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
          Current_Measured                :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En27
          paramCurrentControlI            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En3
          sampleTime                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En24
          paramCurrentControlP            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Voltage                         :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En11
          );
  END COMPONENT;

  COMPONENT Q_Current_Control
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Current_Command                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
          Current_Measured                :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En27
          paramCurrentControlI            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En3
          sampleTime                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En24
          paramCurrentControlP            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Voltage                         :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En11
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : D_Current_Control
    USE ENTITY work.D_Current_Control(rtl);

  FOR ALL : Q_Current_Control
    USE ENTITY work.Q_Current_Control(rtl);

  -- Signals
  SIGNAL D_Command_out1                   : signed(15 DOWNTO 0);  -- sfix16_En12
  SIGNAL D_Current_Control_out1           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Q_Current_Control_out1           : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  -- DQ Current Control

  -- <S2>/D_Current_Control
  u_D_Current_Control : D_Current_Control
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Current_Command => std_logic_vector(D_Command_out1),  -- sfix16_En12
              Current_Measured => D_Current,  -- sfix32_En27
              paramCurrentControlI => paramCurrentControlI,  -- sfix16_En3
              sampleTime => sampleTime,  -- sfix16_En24
              paramCurrentControlP => paramCurrentControlP,  -- sfix16_En8
              Voltage => D_Current_Control_out1  -- sfix16_En11
              );

  -- <S2>/Q_Current_Control
  u_Q_Current_Control : Q_Current_Control
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Current_Command => Q_Command,  -- sfix16_En12
              Current_Measured => Q_Current,  -- sfix32_En27
              paramCurrentControlI => paramCurrentControlI,  -- sfix16_En3
              sampleTime => sampleTime,  -- sfix16_En24
              paramCurrentControlP => paramCurrentControlP,  -- sfix16_En8
              Voltage => Q_Current_Control_out1  -- sfix16_En11
              );

  -- <S2>/D_Command
  D_Command_out1 <= to_signed(16#0000#, 16);

  D_Voltage <= D_Current_Control_out1;

  Q_Voltage <= Q_Current_Control_out1;

END rtl;

