-- -------------------------------------------------------------
-- 
-- File Name: foc_hdl_prj_v3\hdlsrc\FOC_Modified_v3\Saturate_Output_block.vhd
-- Created: 2017-11-28 19:11:02
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Saturate_Output_block
-- Source Path: FOC_Modified_v3/DQ_Current_Control/Q_Current_Control/Saturate_Output
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Saturate_Output_block IS
  PORT( In_rsvd                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En20
        Out_rsvd                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En20
        );
END Saturate_Output_block;


ARCHITECTURE rtl OF Saturate_Output_block IS

  -- Signals
  SIGNAL Saturation_Magntidue_out1        : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL In_signed                        : signed(31 DOWNTO 0);  -- sfix32_En20
  SIGNAL Negate_cast                      : signed(16 DOWNTO 0);  -- sfix17_En11
  SIGNAL Negate_cast_1                    : signed(16 DOWNTO 0);  -- sfix17_En11
  SIGNAL Negate_out1                      : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL Saturation_Dynamic_upper_limit   : signed(31 DOWNTO 0);  -- sfix32_En20
  SIGNAL Saturation_Dynamic_lower_limit   : signed(31 DOWNTO 0);  -- sfix32_En20
  SIGNAL Saturation_Dynamic_out1          : signed(31 DOWNTO 0);  -- sfix32_En20

BEGIN
  -- <S12>/Saturation_Magntidue
  Saturation_Magntidue_out1 <= to_signed(16#6EDA#, 16);

  In_signed <= signed(In_rsvd);

  -- <S12>/Negate
  Negate_cast <= resize(Saturation_Magntidue_out1, 17);
  Negate_cast_1 <=  - (Negate_cast);
  Negate_out1 <= Negate_cast_1(15 DOWNTO 0);

  -- <S12>/Saturation_Dynamic
  Saturation_Dynamic_upper_limit <= resize(Saturation_Magntidue_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);
  Saturation_Dynamic_lower_limit <= resize(Negate_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);
  
  Saturation_Dynamic_out1 <= Saturation_Dynamic_upper_limit WHEN In_signed > Saturation_Dynamic_upper_limit ELSE
      Saturation_Dynamic_lower_limit WHEN In_signed < Saturation_Dynamic_lower_limit ELSE
      In_signed;

  Out_rsvd <= std_logic_vector(Saturation_Dynamic_out1);

END rtl;

