-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\paul.rogers\OldStuff\GradSchool\MATLAB\VF\pwm_hdl_prj\hdlsrc\PWMGenerator_v3\PWMGenerator_v3.vhd
-- Created: 2017-10-05 15:53:18
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2e-06
-- Target subsystem base rate: 2e-06
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWMGenerator_v3
-- Source Path: PWMGenerator_v3
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PWMGenerator_v3 IS
  PORT(
		Va			:	IN		std_logic_vector(83 DOWNTO 0);  -- sfix84_En66
		Vb			:	IN		std_logic_vector(83 DOWNTO 0);  -- sfix84_En66
		Vc			:	IN		std_logic_vector(83 DOWNTO 0);  -- sfix84_En66
		Counter	:	IN		std_logic_vector(7 DOWNTO 0);  -- uint8
		Vahigh	:	OUT	std_logic;
		Vbhigh	:	OUT	std_logic;
		Vchigh	:	OUT	std_logic;
		Valow		:	OUT	std_logic;
		Vblow		:	OUT	std_logic;
		Vclow		:	OUT	std_logic
		);
END PWMGenerator_v3;


ARCHITECTURE rtl OF PWMGenerator_v3 IS

  -- Signals
  SIGNAL Va_signed                        : signed(83 DOWNTO 0);  -- sfix84_En66
  SIGNAL Bias_const_val_1                 : signed(83 DOWNTO 0);  -- sfix84_En66
  SIGNAL Bias_out1                        : signed(83 DOWNTO 0);  -- sfix84_En66
  SIGNAL Counter_unsigned                 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Data_Type_Conversion_out1        : signed(83 DOWNTO 0);  -- sfix84_En66
  SIGNAL vahighcomp_relop1                : std_logic;
  SIGNAL Vb_signed                        : signed(83 DOWNTO 0);  -- sfix84_En66
  SIGNAL Bias1_const_val_1                : signed(83 DOWNTO 0);  -- sfix84_En66
  SIGNAL Bias1_out1                       : signed(83 DOWNTO 0);  -- sfix84_En66
  SIGNAL vbhighcomp_relop1                : std_logic;
  SIGNAL Vc_signed                        : signed(83 DOWNTO 0);  -- sfix84_En66
  SIGNAL Bias2_const_val_1                : signed(83 DOWNTO 0);  -- sfix84_En66
  SIGNAL Bias2_out1                       : signed(83 DOWNTO 0);  -- sfix84_En66
  SIGNAL vchighcomp_relop1                : std_logic;
  SIGNAL Bias3_const_val_1                : signed(83 DOWNTO 0);  -- sfix84_En66
  SIGNAL Bias3_out1                       : signed(83 DOWNTO 0);  -- sfix84_En66
  SIGNAL valowcomp_relop1                 : std_logic;
  SIGNAL Bias4_const_val_1                : signed(83 DOWNTO 0);  -- sfix84_En66
  SIGNAL Bias4_out1                       : signed(83 DOWNTO 0);  -- sfix84_En66
  SIGNAL vblowcomp_relop1                 : std_logic;
  SIGNAL Bias5_const_val_1                : signed(83 DOWNTO 0);  -- sfix84_En66
  SIGNAL Bias5_out1                       : signed(83 DOWNTO 0);  -- sfix84_En66
  SIGNAL vclowcomp_relop1                 : std_logic;

BEGIN
  Va_signed <= signed(Va);

  Bias_const_val_1 <= signed'(X"FFFF60000000000000000");

  Bias_out1 <= Va_signed + Bias_const_val_1;

  Counter_unsigned <= unsigned(Counter);

  Data_Type_Conversion_out1 <= signed(resize(Counter_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 84));

  
  vahighcomp_relop1 <= '1' WHEN Bias_out1 >= Data_Type_Conversion_out1 ELSE
      '0';

  Vb_signed <= signed(Vb);

  Bias1_const_val_1 <= signed'(X"FFFF60000000000000000");

  Bias1_out1 <= Vb_signed + Bias1_const_val_1;

  
  vbhighcomp_relop1 <= '1' WHEN Bias1_out1 >= Data_Type_Conversion_out1 ELSE
      '0';

  Vc_signed <= signed(Vc);

  Bias2_const_val_1 <= signed'(X"FFFF60000000000000000");

  Bias2_out1 <= Vc_signed + Bias2_const_val_1;

  
  vchighcomp_relop1 <= '1' WHEN Bias2_out1 >= Data_Type_Conversion_out1 ELSE
      '0';

  Bias3_const_val_1 <= signed'(X"0000A0000000000000000");

  Bias3_out1 <= Va_signed + Bias3_const_val_1;

  
  valowcomp_relop1 <= '1' WHEN Bias3_out1 <= Data_Type_Conversion_out1 ELSE
      '0';

  Bias4_const_val_1 <= signed'(X"0000A0000000000000000");

  Bias4_out1 <= Vb_signed + Bias4_const_val_1;

  
  vblowcomp_relop1 <= '1' WHEN Bias4_out1 <= Data_Type_Conversion_out1 ELSE
      '0';

  Bias5_const_val_1 <= signed'(X"0000A0000000000000000");

  Bias5_out1 <= Vc_signed + Bias5_const_val_1;

  
  vclowcomp_relop1 <= '1' WHEN Bias5_out1 <= Data_Type_Conversion_out1 ELSE
      '0';

  Vahigh <= vahighcomp_relop1;

  Vbhigh <= vbhighcomp_relop1;

  Vchigh <= vchighcomp_relop1;

  Valow <= valowcomp_relop1;

  Vblow <= vblowcomp_relop1;

  Vclow <= vclowcomp_relop1;

END rtl;

